use clap::{Arg, Command};

pub fn build_cli() -> Command {
  Command::new("ferrum")
    .about("A simple CLI tool for ferrum projects")
    .subcommand(Command::new("new")
      .about("Create new ferrum project using cargo."))
    .subcommand(Command::new("build")
      .about("Build ferrum project using cargo."))
    .subcommand(Command::new("deploy")
      .about("Deploy ferrum project using serverless framework.")
      .arg(Arg::new("bin_name")
        .long("bin")
        .value_name("BIN_NAME")
        .help("Specify the binary target name")
        .required(true))
      .arg(Arg::new("lambda_name")
        .long("lambda")
        .value_name("LAMBDA_NAME")
        .help("Specify the lambda name")
        .required(true))
      .arg(Arg::new("profile_name")
        .long("profile")
        .value_name("PROFILE_NAME")
        .help("Specify the profile name")
        .required(true)))
}
